### ISSUE TITLE
test.py results in black image

### ISSUE THREAD

**Issue by zizo1111** [PingoLH/FCHarDNet#18]
Hallo, 
thanks for the nice effort. I have been trying to test the pretrained models but i am unsuccessful as the result is always a black image. 

update: the problem was decoding the segmap

**Comment by huang45** [comment]
Hi, Have you solve that? same question.

**Comment by animesh-007** [comment]
Hello. I am facing the same issue. Can anyone guide me on how to solve this?

**Comment by Junchan123** [comment]
@zizo1111 Hello, could you inform me on how you solved the issue? Thank you.

**Comment by MBKS1** [comment]
Hello, I'm encountering the same issue, did you solve it? @Junchan123 @animesh-007 @huang45

**Comment by animesh-007** [comment]
Hi. I solved this by implementing the methodology used in `validate.py`.
