### ISSUE TITLE
Black image after testing on custom image

### ISSUE THREAD

**Issue by MBKS1** [PingoLH/FCHarDNet#58]
Hello,
After the training & validation of HardNet on Cityscapes, I wanted to test the model on some custom images.
The script doesnt return any errors but the result is always a black image.

Did anyone encounter this issue ? How can I fix it ?

Thanks,

**Comment by animesh-007** [comment]
You can try to use the same method used in `validate.py` in `test.py` to solve this issue.

**Comment by MBKS1** [comment]
@animesh-007 thanks for your reply.

I fixed the issue by changing the following : 

rgb[:,:,0] = r / 255.0
rgb[:,:,1] = g / 255.0
rgb[:,:,2] = b / 255.0

to

rgb[:,:,0] = r
rgb[:,:,1] = g
rgb[:,:,2] = b

in the Cityscapes Loader (FCHarDNet/ptsemseg/loader/cityscapes_loader.py).
