### ISSUE TITLE
Per-category IOU 

### ISSUE THREAD

**Issue by lxtGH** [PingoLH/FCHarDNet#6]
Hi !!  Could you show  the per-category IoU results in Cityscape?

**Comment by PingoLH** [comment]
Hello, thanks for reaching out. Yes for sure. Please refer to our public submission (75.9)
https://www.cityscapes-dataset.com/method-details/?submissionID=5468
For the updated result with color jitter training (76.0), please refer to:
https://www.cityscapes-dataset.com/anonymous-results/?id=71caf12fe70be7a06152db1c0a0d74511d8b19520132f8dc24aab54d21c9ff9b

**Comment by lxtGH** [comment]
Thank you !!
